# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-21 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='\u6587\u6863\u6807\u9898')),
                ('doc_url', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='\u6587\u6863\u8def\u5f84')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u6587\u6863\u5907\u6ce8')),
            ],
            options={
                'db_table': 'doc_info',
                'verbose_name': '\u516c\u53f8\u6587\u6863',
                'verbose_name_plural': '\u516c\u53f8\u6587\u6863',
            },
        ),
        migrations.CreateModel(
            name='mail_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.EmailField(max_length=254, verbose_name='\u53d1\u4ef6\u5730\u5740')),
                ('passwd', models.CharField(max_length=48, verbose_name='\u90ae\u7bb1\u5bc6\u7801')),
                ('server', models.URLField(verbose_name='\u53d1\u9001\u5730\u5740')),
                ('port', models.IntegerField(default=465, verbose_name='\u53d1\u9001\u7aef\u53e3')),
                ('head', models.CharField(max_length=48, verbose_name='\u90ae\u4ef6\u6807\u9898')),
                ('remark', models.CharField(max_length=24, verbose_name='\u5730\u5740\u5907\u6ce8')),
                ('mail_remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'mail_info',
                'verbose_name': '\u90ae\u4ef6\u914d\u7f6e',
                'verbose_name_plural': '\u90ae\u4ef6\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='nav_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='\u5bfc\u822a\u540d\u79f0')),
                ('navurl', models.URLField(verbose_name='\u5bfc\u822a\u5730\u5740')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'nav_info',
                'verbose_name': '\u5bfc\u822a\u7ba1\u7406',
                'verbose_name_plural': '\u5bfc\u822a\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='nav_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7c7b\u578b\u540d\u79f0')),
            ],
            options={
                'db_table': 'nav_types',
                'verbose_name': '\u5bfc\u822a\u7c7b\u578b',
                'verbose_name_plural': '\u5bfc\u822a\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Structure_accesskey_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesskey_id', models.CharField(max_length=48, verbose_name='AccesskeyID')),
            ],
            options={
                'db_table': 'Structure_accesskey_id',
                'verbose_name': 'AccesskeyID',
                'verbose_name_plural': 'AccesskeyID',
            },
        ),
        migrations.CreateModel(
            name='Structure_appname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apppname', models.CharField(max_length=48, verbose_name='\u5e94\u7528\u540d\u79f0')),
            ],
            options={
                'db_table': 'Structure_appname',
                'verbose_name': '\u5e94\u7528\u540d\u79f0',
                'verbose_name_plural': '\u5e94\u7528\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Structure_data_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=48, verbose_name='RDS\u6216Redis-ID')),
            ],
            options={
                'db_table': 'Structure_data_id',
                'verbose_name': 'RDS\u6216Redis-ID',
                'verbose_name_plural': 'RDS\u6216Redis-ID',
            },
        ),
        migrations.CreateModel(
            name='Structure_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=48, verbose_name='\u4f7f\u7528\u8005')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='\u4f7f\u7528\u8005Email')),
                ('app_remark', models.CharField(max_length=48, verbose_name='\u5e94\u7528\u540d\u5907\u6ce8\u8bf4\u660e')),
                ('data_user', models.CharField(max_length=48, verbose_name='RDS\u6216Redis\u7528\u6237\u540d')),
                ('data_remark', models.CharField(max_length=96, verbose_name='RDS\u6216Redis\u5907\u6ce8\u8bf4\u660e')),
                ('accesskey_remark', models.CharField(max_length=96, verbose_name='AccesskeyID\u5907\u6ce8\u8bf4\u660e')),
                ('oss_remark', models.TextField(max_length=256, verbose_name='OSS\u64cd\u4f5c\u5bf9\u8c61\u8bf4\u660e')),
                ('mail_remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('accesskey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Structure_accesskey_id', verbose_name='AccesskeyID')),
                ('appname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Structure_appname', verbose_name='\u5e94\u7528\u540d')),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Structure_data_id', verbose_name='RDS\u6216Redis-ID')),
            ],
            options={
                'db_table': 'Structure_info',
                'verbose_name': '\u5e94\u7528\u5173\u7cfb',
                'verbose_name_plural': '\u5e94\u7528\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='Structure_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=24, verbose_name='\u5f52\u5c5e\u9879\u76ee')),
            ],
            options={
                'db_table': 'Structure_project',
                'verbose_name': '\u5f52\u5c5e\u9879\u76ee',
                'verbose_name_plural': '\u5f52\u5c5e\u9879\u76ee',
            },
        ),
        migrations.AddField(
            model_name='Structure_info',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Structure_project', verbose_name='\u5f52\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='nav_info',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.nav_types', verbose_name='\u5bfc\u822a\u7c7b\u578b'),
        ),
    ]
