# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_dns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='\u89e3\u6790\u5e73\u53f0')),
                ('addr', models.CharField(max_length=48, verbose_name='\u7ba1\u7406\u5730\u5740')),
                ('user', models.CharField(max_length=48, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=48, verbose_name='\u5bc6\u7801')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'domain_dns',
                'verbose_name': '\u6ce8\u518c\u5546',
                'verbose_name_plural': '\u6ce8\u518c\u5546',
            },
        ),
        migrations.CreateModel(
            name='domain_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domian', models.URLField(max_length=96, verbose_name='\u57df\u540d')),
                ('expire', models.DateTimeField(verbose_name='\u5230\u671f\u65f6\u95f4')),
                ('beian_id', models.CharField(max_length=48, null=True, verbose_name='\u5907\u6848\u7f16\u53f7')),
                ('beian_ip', models.CharField(max_length=48, null=True, verbose_name='\u5907\u6848IP')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'domain_info',
                'verbose_name': '\u57df\u540d\u7ba1\u7406',
                'verbose_name_plural': '\u57df\u540d\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='domain_jieru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='\u5907\u6848\u63a5\u5165\u5546')),
                ('addr', models.CharField(max_length=48, verbose_name='\u7ba1\u7406\u5730\u5740')),
                ('user', models.CharField(max_length=48, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=48, verbose_name='\u5bc6\u7801')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'domain_jieru',
                'verbose_name': '\u5907\u6848\u63a5\u5165\u5546',
                'verbose_name_plural': '\u5907\u6848\u63a5\u5165\u5546',
            },
        ),
        migrations.CreateModel(
            name='domain_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='\u7f51\u7ad9\u8d1f\u8d23\u4eba')),
                ('num', models.CharField(max_length=48, verbose_name='\u8bc1\u4ef6\u53f7')),
                ('phone', models.CharField(max_length=48, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'domain_manager',
                'verbose_name': '\u7f51\u7ad9\u8d1f\u8d23\u4eba',
                'verbose_name_plural': '\u7f51\u7ad9\u8d1f\u8d23\u4eba',
            },
        ),
        migrations.CreateModel(
            name='domain_owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=48, verbose_name='\u57df\u540d\u6301\u6709\u8005')),
                ('beian', models.CharField(max_length=48, verbose_name='\u5907\u6848\u53f7\u4e3b\u53f7')),
                ('num', models.CharField(max_length=48, verbose_name='\u8bc1\u4ef6\u53f7')),
                ('phone', models.CharField(max_length=48, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'domain_owner',
                'verbose_name': '\u57df\u540d\u6301\u6709\u8005',
                'verbose_name_plural': '\u57df\u540d\u6301\u6709\u8005',
            },
        ),
        migrations.CreateModel(
            name='domain_supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='\u6ce8\u518c\u5546')),
                ('addr', models.CharField(max_length=48, verbose_name='\u7ba1\u7406\u5730\u5740')),
                ('user', models.CharField(max_length=48, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=48, verbose_name='\u5bc6\u7801')),
                ('remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'domain_supplier',
                'verbose_name': '\u6ce8\u518c\u5546',
                'verbose_name_plural': '\u6ce8\u518c\u5546',
            },
        ),
        migrations.AlterField(
            model_name='doc_info',
            name='doc_url',
            field=models.FileField(upload_to='img/', verbose_name='\u6587\u6863\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='doc_info',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u6587\u6863\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='domain_info',
            name='beian_jieru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.domain_jieru', verbose_name='\u5907\u6848\u63a5\u5165\u5546'),
        ),
        migrations.AddField(
            model_name='domain_info',
            name='domain_dns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.domain_dns', verbose_name='\u89e3\u6790\u7ba1\u7406\u5e73\u53f0'),
        ),
        migrations.AddField(
            model_name='domain_info',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.domain_manager', verbose_name='\u7f51\u7ad9\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='domain_info',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.domain_owner', verbose_name='\u8bc1\u4e66\u6301\u6709\u8005'),
        ),
        migrations.AddField(
            model_name='domain_info',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.domain_supplier', verbose_name='\u6ce8\u518c\u5546'),
        ),
    ]
