# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail_info',
            options={'verbose_name': '\u90ae\u4ef6\u914d\u7f6e', 'verbose_name_plural': '\u90ae\u4ef6\u914d\u7f6e'},
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='head',
            field=models.CharField(max_length=48, null=True, verbose_name='\u90ae\u4ef6\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='port',
            field=models.IntegerField(default=465, verbose_name='\u53d1\u9001\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='remark',
            field=models.CharField(max_length=24, null=True, verbose_name='\u5730\u5740\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='send',
            field=models.EmailField(max_length=254, verbose_name='\u53d1\u4ef6\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='server',
            field=models.URLField(null=True, verbose_name='\u53d1\u9001\u5730\u5740'),
        ),
    ]
