# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180912_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_info',
            name='head',
            field=models.CharField(default=django.utils.timezone.now, max_length=48, verbose_name='\u90ae\u4ef6\u6807\u9898'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='passwd',
            field=models.CharField(default=2, max_length=48, verbose_name='\u90ae\u7bb1\u5bc6\u7801'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='remark',
            field=models.CharField(max_length=24, verbose_name='\u5730\u5740\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='mail_info',
            name='server',
            field=models.URLField(verbose_name='\u53d1\u9001\u5730\u5740'),
        ),
    ]
