# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20180928_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain_owner',
            options={'verbose_name': '\u5907\u6848\u53f7\u4e3b\u53f7', 'verbose_name_plural': '\u5907\u6848\u53f7\u4e3b\u53f7'},
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.domain_owner', verbose_name='\u5907\u6848\u53f7\u4e3b\u53f7'),
        ),
    ]
