# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import itresource.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itres_approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.CharField(max_length=8, verbose_name='\u5ba1\u6279\u4eba')),
                ('approver_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'db_table': 'Itres_approver',
                'verbose_name': '\u5ba1\u6279\u4eba',
                'verbose_name_plural': '\u5ba1\u6279\u4eba',
            },
        ),
        migrations.CreateModel(
            name='Itres_cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=8, verbose_name='\u4f7f\u7528\u5468\u671f')),
            ],
            options={
                'db_table': 'Itres_cycle',
                'verbose_name': '\u4f7f\u7528\u5468\u671f',
                'verbose_name_plural': '\u4f7f\u7528\u5468\u671f',
            },
        ),
        migrations.CreateModel(
            name='Itres_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=14, verbose_name='\u7533\u8bf7\u90e8\u95e8')),
            ],
            options={
                'db_table': 'Itres_department',
                'verbose_name': '\u7533\u8bf7\u90e8\u95e8',
                'verbose_name_plural': '\u7533\u8bf7\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='Itres_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('res_applicant', models.CharField(max_length=12, verbose_name='\u7533\u8bf7\u4eba')),
                ('res_applicat_email', models.EmailField(max_length=254, verbose_name='\u7533\u8bf7\u4ebaEmail')),
                ('res_details', models.TextField(blank=True, max_length=128, verbose_name='\u8d44\u6e90\u8be6\u60c5')),
                ('res_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('res_association_id', models.CharField(default=itresource.models.pkgen, max_length=8, verbose_name='\u5173\u8054ID')),
                ('res_remark', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('res_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itresource.Itres_approver', verbose_name='\u5ba1\u6279\u4eba')),
                ('res_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itresource.Itres_cycle', verbose_name='\u4f7f\u7528\u5468\u671f')),
                ('res_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itresource.Itres_department', verbose_name='\u7533\u8bf7\u90e8\u95e8')),
            ],
            options={
                'db_table': 'Itres_info',
                'verbose_name': '\u8d44\u6e90\u7ba1\u7406',
                'verbose_name_plural': '\u8d44\u6e90\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Itres_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=14, verbose_name='\u5f52\u5c5e\u9879\u76ee')),
            ],
            options={
                'db_table': 'Itres_project',
                'verbose_name': '\u5f52\u5c5e\u9879\u76ee',
                'verbose_name_plural': '\u5f52\u5c5e\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Itres_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=8, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'Itres_status',
                'verbose_name': '\u72b6\u6001',
                'verbose_name_plural': '\u72b6\u6001',
            },
        ),
        migrations.CreateModel(
            name='Itres_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=14, verbose_name='\u8d44\u6e90\u7c7b\u578b')),
            ],
            options={
                'db_table': 'Itres_types',
                'verbose_name': '\u8d44\u6e90\u7c7b\u578b',
                'verbose_name_plural': '\u8d44\u6e90\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='itres_info',
            name='res_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itresource.Itres_project', verbose_name='\u5f52\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='itres_info',
            name='res_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itresource.Itres_status', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='itres_info',
            name='res_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itresource.Itres_types', verbose_name='\u8d44\u6e90\u7c7b\u578b'),
        ),
    ]
