# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itresource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itres_info',
            name='res_resid',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='\u8d44\u6e90ID'),
        ),
    ]
